### PR TITLE
Replace npm expandions with nthnchu expandions

### PR DESCRIPTION
**Pull request by Ryyn-Sd**
The bad news is that when I push, it doesn't update like how it is supposed to.

### CODE REVIEW

**Comment by nthnchu** [comment]
Hmm. Thanks for your PR but I don't really understand it. Why is it ntn? And why should I accept this?

**Comment by Ryyn-Sd** [comment]
OK. ntn is for *n*a*t*ha*n*. Also, why do you want to get rid of it?

**Comment by Ryyn-Sd** [comment]
And why won't github actions commit?

**Comment by nthnchu** [comment]
Yeah I don't really understand it. I'm going to close this but I will consider other PRs if you send them.

**Comment by Ryyn-Sd** [comment]
OK

**Pull request closed without merging**
